# Generated by Django 3.1.3 on 2020-11-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=150)),
                ('private', models.CharField(max_length=150)),
                ('html_url', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('fork', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=150)),
                ('archive_url', models.CharField(max_length=150)),
                ('assignees_url', models.CharField(max_length=150)),
                ('blobs_url', models.CharField(max_length=150)),
                ('branches_url', models.CharField(max_length=150)),
                ('collaborators_url', models.CharField(max_length=150)),
                ('comments_url', models.CharField(max_length=150)),
                ('commits_url', models.CharField(max_length=150)),
                ('compare_url', models.CharField(max_length=150)),
                ('contents_url', models.CharField(max_length=150)),
                ('contributors_url', models.CharField(max_length=150)),
                ('deployments_url', models.CharField(max_length=150)),
                ('downloads_url', models.CharField(max_length=150)),
                ('events_url', models.CharField(max_length=150)),
                ('forks_url', models.CharField(max_length=150)),
                ('git_commits_url', models.CharField(max_length=150)),
                ('git_refs_url', models.CharField(max_length=150)),
                ('git_tags_url', models.CharField(max_length=150)),
                ('issue_comment_url', models.CharField(max_length=150)),
                ('issue_events_url', models.CharField(max_length=150)),
                ('issues_url', models.CharField(max_length=150)),
                ('keys_url', models.CharField(max_length=150)),
                ('labels_url', models.CharField(max_length=150)),
                ('languages_url', models.CharField(max_length=150)),
                ('merges_url', models.CharField(max_length=150)),
                ('milestones_url', models.CharField(max_length=150)),
                ('notifications_url', models.CharField(max_length=150)),
                ('pulls_url', models.CharField(max_length=150)),
                ('releases_url', models.CharField(max_length=150)),
                ('stargazers_url', models.CharField(max_length=150)),
                ('statuses_url', models.CharField(max_length=150)),
                ('subscribers_url', models.CharField(max_length=150)),
                ('subscription_url', models.CharField(max_length=150)),
                ('tags_url', models.CharField(max_length=150)),
                ('teams_url', models.CharField(max_length=150)),
                ('trees_url', models.CharField(max_length=150)),
                ('hooks_url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('node_id', models.CharField(max_length=150)),
                ('avatar_url', models.CharField(max_length=150)),
                ('gravatar_id', models.CharField(max_length=150)),
                ('html_url', models.CharField(max_length=150)),
                ('followers_url', models.CharField(max_length=150)),
                ('following_url', models.CharField(max_length=150)),
                ('gists_url', models.CharField(max_length=150)),
                ('starred_url', models.CharField(max_length=150)),
                ('subscriptions_url', models.CharField(max_length=150)),
                ('organizations_url', models.CharField(max_length=150)),
                ('repos_url', models.CharField(max_length=150)),
                ('events_url', models.CharField(max_length=150)),
                ('received_events_url', models.CharField(max_length=150)),
                ('site_admin', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('blog', models.CharField(max_length=150)),
                ('public_repos', models.CharField(max_length=150)),
                ('repositories', models.ManyToManyField(to='public_github_scrapper.Repository', verbose_name='list of repositories')),
            ],
        ),
    ]
